import SearchResult from './SearchResult.js';
const mockSearchData = [
  {
    answer: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
    bbox: [413.58, 515.65, 584.74, 634.4199999999997],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer:
      '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021/nEBIT -15%/+0.5% in 2020/2021./nEBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019/nYields EPS of ~$4.00 in both 2020/2021/nCOVID-19 is a less signiﬁcant tailwind than in our base case./nCost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
    group_type: 'same_location',
    header_semantic_terms: [],
    header_semantic_terms_terms: [],
    header_text: '~13x 2021e EPS of ~$4.00',
    header_text_terms: [],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'WSM Financial Statements',
      'Risk Reward – Williams-Sonoma Inc (WSM.N)',
      'Playbook Working, but Priced In',
      'PRICE TARGET',
      ' BULL CASE',
      'BEAR CASE',
      '~13x 2021e EPS of ~$4.00',
    ],
    hierarchy_headers_text_terms: [],
    is_override: false,
    key: 2,
    match_idx: 1226,
    match_score: 1,
    match_semantic_terms: [],
    match_text_terms: [],
    matches: [
      {
        answer: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1226,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'a6706f42',
      },
      {
        answer: 'EBIT -15%/+0.5% in 2020/2021.',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: 'EBIT -15%/+0.5% in 2020/2021.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1230,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'Translates to EBIT -15%/+0.5% in 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '03d6d108',
      },
      {
        answer: 'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1231,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '0c0c8d9a',
      },
      {
        answer: 'Yields EPS of ~$4.00 in both 2020/2021',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: 'Yields EPS of ~$4.00 in both 2020/2021',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1232,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'Yields EPS of ~$4.00 in both 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'b1b184f0',
      },
      {
        answer: 'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: ['BEAR', 'CASE', 'CASE', 'OLLI'],
        is_override: false,
        match_idx: 1227,
        match_score: 0.5487457907899606,
        match_semantic_terms: ['less'],
        match_text_terms: ['case'],
        page_idx: 22,
        phrase: 'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        relevancy_score: 1,
        scaled_score: 0.5487457907899606,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'bf13b091',
      },
      {
        answer:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: ['BEAR', 'CASE', 'CASE', 'OLLI'],
        is_override: false,
        match_idx: 1229,
        match_score: 0.5476900578969224,
        match_semantic_terms: ['cost', 'Cost', 'followed', 'impact', 'less'],
        match_text_terms: ['case'],
        page_idx: 22,
        phrase:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        relevancy_score: 1,
        scaled_score: 0.5476900578969224,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '4703311c',
      },
    ],
    page_idx: 22,
    phrase: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021.',
    relevancy_score: 1,
    scaled_score: 1,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: 'a6706f42',
  },
  {
    answer: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
    bbox: [413.58, 515.65, 584.74, 634.4199999999997],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer:
      '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021/nEBIT -15%/+0.5% in 2020/2021./nEBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019/nYields EPS of ~$4.00 in both 2020/2021/nCOVID-19 is a less signiﬁcant tailwind than in our base case./nCost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
    group_type: 'same_location',
    header_semantic_terms: [],
    header_semantic_terms_terms: [],
    header_text: '~13x 2021e EPS of ~$4.00',
    header_text_terms: [],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'WSM Financial Statements',
      'Risk Reward – Williams-Sonoma Inc (WSM.N)',
      'Playbook Working, but Priced In',
      'PRICE TARGET',
      ' BULL CASE',
      'BEAR CASE',
      '~13x 2021e EPS of ~$4.00',
    ],
    hierarchy_headers_text_terms: [],
    is_override: false,
    key: 2,
    match_idx: 1226,
    match_score: 1,
    match_semantic_terms: [],
    match_text_terms: [],
    matches: [
      {
        answer: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1226,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'a6706f42',
      },
      {
        answer: 'EBIT -15%/+0.5% in 2020/2021.',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: 'EBIT -15%/+0.5% in 2020/2021.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1230,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'Translates to EBIT -15%/+0.5% in 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '03d6d108',
      },
      {
        answer: 'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1231,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'EBIT margin contracts to 7.6% in 2021 vs. 8.6% in 2019.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '0c0c8d9a',
      },
      {
        answer: 'Yields EPS of ~$4.00 in both 2020/2021',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: 'Yields EPS of ~$4.00 in both 2020/2021',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1232,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'Yields EPS of ~$4.00 in both 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'b1b184f0',
      },
      {
        answer: 'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: ['BEAR', 'CASE', 'CASE', 'OLLI'],
        is_override: false,
        match_idx: 1227,
        match_score: 0.5487457907899606,
        match_semantic_terms: ['less'],
        match_text_terms: ['case'],
        page_idx: 22,
        phrase: 'COVID-19 is a less signiﬁcant tailwind than in our base case.',
        relevancy_score: 1,
        scaled_score: 0.5487457907899606,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'bf13b091',
      },
      {
        answer:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        bbox: [413.58, 515.65, 584.74, 634.4199999999997],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~13x 2021e EPS of ~$4.00',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~13x 2021e EPS of ~$4.00',
        ],
        hierarchy_headers_text_terms: ['BEAR', 'CASE', 'CASE', 'OLLI'],
        is_override: false,
        match_idx: 1229,
        match_score: 0.5476900578969224,
        match_semantic_terms: ['cost', 'Cost', 'followed', 'impact', 'less'],
        match_text_terms: ['case'],
        page_idx: 22,
        phrase:
          'Cost cuts blunt the impact of gross margin contraction on the P&L in 2020, followed by cost growth in 2021 as WSM reinvests in the business (with less expense leverage than our base case).',
        relevancy_score: 1,
        scaled_score: 0.5476900578969224,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '4703311c',
      },
    ],
    page_idx: 22,
    phrase: '+1%/-2% comps in 2020/2021.+1%/-2% comps in 2020/2021.',
    relevancy_score: 1,
    scaled_score: 1,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: 'a6706f42',
  },
  {
    answer:
      'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%).',
    bbox: [413.58, 573.04, 583.52, 671.8499999999999],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer:
      'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%)./nExecution missteps continue and closeout deals fail to resonate with consumers./ncomps fall to -2%, and paired with EBIT margin declines and reduced store growth beginning in 2021, EPS growth declines in the medium-term./nWe model EPS of ~$1.85/~$1.75 in 2020/2021',
    group_type: 'same_location',
    header_semantic_terms: [],
    header_semantic_terms_terms: [],
    header_text: '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
    header_text_terms: [],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'WSM Financial Statements',
      "Risk Reward – Ollie's Bargain Outlet Holdings Inc (OLLI.O)",
      'Differentiated Value Proposition; Execution Uncertainties Reﬂected in Valuation',
      'PRICE TARGET',
      ' BULL CASE',
      'BEAR CASE',
      '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
    ],
    hierarchy_headers_text_terms: [],
    is_override: false,
    key: 1,
    match_idx: 1119,
    match_score: 1,
    match_semantic_terms: [],
    match_text_terms: [],
    matches: [
      {
        answer:
          'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%).',
        bbox: [413.58, 573.04, 583.52, 671.8499999999999],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%).',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          "Risk Reward – Ollie's Bargain Outlet Holdings Inc (OLLI.O)",
          'Differentiated Value Proposition; Execution Uncertainties Reﬂected in Valuation',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1119,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 20,
        phrase:
          'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%).',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '3fe1899c',
      },
      {
        answer:
          'Execution missteps continue and closeout deals fail to resonate with consumers.',
        bbox: [413.58, 573.04, 583.52, 671.8499999999999],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'Execution missteps continue and closeout deals fail to resonate with consumers.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          "Risk Reward – Ollie's Bargain Outlet Holdings Inc (OLLI.O)",
          'Differentiated Value Proposition; Execution Uncertainties Reﬂected in Valuation',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1120,
        match_score: 1,
        match_semantic_terms: ['fail', 'continue'],
        match_text_terms: [],
        page_idx: 20,
        phrase:
          'Execution missteps continue and closeout deals fail to resonate with consumers.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '0cc7aede',
      },
      {
        answer:
          'comps fall to -2%, and paired with EBIT margin declines and reduced store growth beginning in 2021, EPS growth declines in the medium-term.',
        bbox: [413.58, 573.04, 583.52, 671.8499999999999],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          'comps fall to -2%, and paired with EBIT margin declines and reduced store growth beginning in 2021, EPS growth declines in the medium-term.',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          "Risk Reward – Ollie's Bargain Outlet Holdings Inc (OLLI.O)",
          'Differentiated Value Proposition; Execution Uncertainties Reﬂected in Valuation',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1121,
        match_score: 1,
        match_semantic_terms: ['fall', 'beginning'],
        match_text_terms: [],
        page_idx: 20,
        phrase:
          'Longer-term, comps fall to -2%, and paired with EBIT margin declines and reduced store growth beginning in 2021, EPS growth declines in the medium-term.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'ddd072f8',
      },
      {
        answer: 'We model EPS of ~$1.85/~$1.75 in 2020/2021',
        bbox: [413.58, 573.04, 583.52, 671.8499999999999],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: 'We model EPS of ~$1.85/~$1.75 in 2020/2021',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          "Risk Reward – Ollie's Bargain Outlet Holdings Inc (OLLI.O)",
          'Differentiated Value Proposition; Execution Uncertainties Reﬂected in Valuation',
          'PRICE TARGET',
          ' BULL CASE',
          'BEAR CASE',
          '~17.5x 2021e EPS of ~$1.75, or ~10x EV/EBITDA',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1122,
        match_score: 1,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 20,
        phrase: 'We model EPS of ~$1.85/~$1.75 in 2020/2021.',
        relevancy_score: 1,
        scaled_score: 1,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '2ce8a704',
      },
    ],
    page_idx: 20,
    phrase:
      'COVID-19 presents a more signiﬁcant, longer-lasting comp headwind than anticipated (2020e comps of -2.5%).',
    relevancy_score: 1,
    scaled_score: 1,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: '3fe1899c',
  },
  {
    answer: '$218',
    bbox: [42.07, 469.19, 362.62, 633.9999999999998],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer: '$218',
    group_type: 'single',
    header_semantic_terms: ['May'],
    header_semantic_terms_terms: [],
    header_text: 'May 29, 2020 05:09 AM GMT',
    header_text_terms: [],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'Earnings',
      '|| North America North America',
      "WHAT'S CHANGED",
      'May 29, 2020 05:09 AM GMT',
    ],
    hierarchy_headers_text_terms: [],
    is_override: false,
    key: 3,
    match_idx: 69,
    match_score: 0.7561584427544287,
    match_semantic_terms: [],
    match_text_terms: ['price', 'target'],
    page_idx: 1,
    phrase: 'Raising price target to $218 (from $200).',
    relevancy_score: 1,
    scaled_score: 0.7561584427544287,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: '6aaced24',
  },
  {
    answer: '$75',
    bbox: [40.97, 151.85000000000002, 392.21000000000004, 180.80000000000004],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer: '$75/n~7.5x our 2021e EBITDA of ~$745m',
    group_type: 'same_location',
    header_semantic_terms: [],
    header_semantic_terms_terms: [],
    header_text: 'PRICE TARGET',
    header_text_terms: ['PRICE', 'TARGET'],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'WSM Financial Statements',
      'Risk Reward – Williams-Sonoma Inc (WSM.N)',
      'Playbook Working, but Priced In',
      'PRICE TARGET',
    ],
    hierarchy_headers_text_terms: ['PRICE', 'TARGET', 'Priced'],
    is_override: false,
    key: 2,
    match_idx: 1173,
    match_score: 0.999654071532032,
    match_semantic_terms: [],
    match_text_terms: ['price', 'target'],
    matches: [
      {
        answer: '$75',
        bbox: [
          40.97, 151.85000000000002, 392.21000000000004, 180.80000000000004,
        ],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: '$75',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: 'PRICE TARGET',
        header_text_terms: ['PRICE', 'TARGET'],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
        ],
        hierarchy_headers_text_terms: ['PRICE', 'TARGET', 'Priced'],
        is_override: false,
        match_idx: 1173,
        match_score: 0.999654071532032,
        match_semantic_terms: [],
        match_text_terms: ['price', 'target'],
        page_idx: 22,
        phrase: 'Our $75 price target reﬂects ~15x our 2021e EPS of ~5.00.',
        relevancy_score: 1,
        scaled_score: 0.999654071532032,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: '477543fd',
      },
      {
        answer: '~7.5x our 2021e EBITDA of ~$745m',
        bbox: [
          40.97, 151.85000000000002, 392.21000000000004, 180.80000000000004,
        ],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: '~7.5x our 2021e EBITDA of ~$745m',
        group_type: 'same_location',
        header_semantic_terms: ['TARGET', 'PRICE'],
        header_semantic_terms_terms: [],
        header_text: 'PRICE TARGET',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Williams-Sonoma Inc (WSM.N)',
          'Playbook Working, but Priced In',
          'PRICE TARGET',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 1174,
        match_score: 0.613595552498591,
        match_semantic_terms: [],
        match_text_terms: [],
        page_idx: 22,
        phrase: 'It equates to ~7.5x our 2021e EBITDA of ~$745m.',
        relevancy_score: 1,
        scaled_score: 0.613595552498591,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'd5cd1487',
      },
    ],
    page_idx: 22,
    phrase: 'Our $75 price target reﬂects ~15x our 2021e EPS of ~5.00.',
    relevancy_score: 1,
    scaled_score: 0.999654071532032,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: '477543fd',
  },
  {
    answer: '$105',
    bbox: [40.97, 151.85000000000002, 398.19000000000005, 200.76000000000005],
    block_text_terms: [],
    block_type: 'para',
    file_score: 0,
    formatted_answer:
      "$105/n~2x premium to DLTR's longer-run average of ~17x (range 12-22x), which is warranted given expected sales uplifts across both banners and positive EBIT/EPS growth outlooks (following two years of declines), driven by COVID-19 disruption and a likely recessionary environment, in which the company should beneﬁt.",
    group_type: 'same_location',
    header_semantic_terms: [],
    header_semantic_terms_terms: [],
    header_text: 'PRICE TARGET',
    header_text_terms: ['PRICE', 'TARGET'],
    hierarchy_headers: [
      'DLTR, ULTA, OLLI & WSM',
      'WSM Financial Statements',
      'Risk Reward – Dollar Tree Inc (DLTR.O)',
      'Top Line Progress Offset by Margin Inconsistency; COVID-19 a Tailwind',
      'PRICE TARGET',
    ],
    hierarchy_headers_text_terms: ['PRICE', 'TARGET'],
    is_override: false,
    key: 1,
    match_idx: 843,
    match_score: 0.999917135005772,
    match_semantic_terms: ['based'],
    match_text_terms: ['price', 'target'],
    matches: [
      {
        answer: '$105',
        bbox: [
          40.97, 151.85000000000002, 398.19000000000005, 200.76000000000005,
        ],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer: '$105',
        group_type: 'same_location',
        header_semantic_terms: [],
        header_semantic_terms_terms: [],
        header_text: 'PRICE TARGET',
        header_text_terms: ['PRICE', 'TARGET'],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Dollar Tree Inc (DLTR.O)',
          'Top Line Progress Offset by Margin Inconsistency; COVID-19 a Tailwind',
          'PRICE TARGET',
        ],
        hierarchy_headers_text_terms: ['PRICE', 'TARGET'],
        is_override: false,
        match_idx: 843,
        match_score: 0.999917135005772,
        match_semantic_terms: ['based'],
        match_text_terms: ['price', 'target'],
        page_idx: 16,
        phrase:
          'Our $105 price target is based on ~19x our 2021e EPS of ~$5.55 (or ~10.5x 2021e EBITDA).',
        relevancy_score: 1,
        scaled_score: 0.999917135005772,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'f4d10248',
      },
      {
        answer:
          "~2x premium to DLTR's longer-run average of ~17x (range 12-22x), which is warranted given expected sales uplifts across both banners and positive EBIT/EPS growth outlooks (following two years of declines), driven by COVID-19 disruption and a likely recessionary environment, in which the company should beneﬁt.",
        bbox: [
          40.97, 151.85000000000002, 398.19000000000005, 200.76000000000005,
        ],
        block_text_terms: [],
        block_type: 'para',
        file_score: 0,
        formatted_answer:
          "~2x premium to DLTR's longer-run average of ~17x (range 12-22x), which is warranted given expected sales uplifts across both banners and positive EBIT/EPS growth outlooks (following two years of declines), driven by COVID-19 disruption and a likely recessionary environment, in which the company should beneﬁt.",
        group_type: 'same_location',
        header_semantic_terms: ['TARGET', 'PRICE'],
        header_semantic_terms_terms: [],
        header_text: 'PRICE TARGET',
        header_text_terms: [],
        hierarchy_headers: [
          'DLTR, ULTA, OLLI & WSM',
          'WSM Financial Statements',
          'Risk Reward – Dollar Tree Inc (DLTR.O)',
          'Top Line Progress Offset by Margin Inconsistency; COVID-19 a Tailwind',
          'PRICE TARGET',
        ],
        hierarchy_headers_text_terms: [],
        is_override: false,
        match_idx: 844,
        match_score: 0.613595552498591,
        match_semantic_terms: [
          'two',
          'sales',
          'across',
          'following',
          'given',
          'premium',
          'likely',
        ],
        match_text_terms: [],
        page_idx: 16,
        phrase:
          "This is a ~2x premium to DLTR's longer-run average of ~17x (range 12-22x), which is warranted given expected sales uplifts across both banners and positive EBIT/EPS growth outlooks (following two years of declines), driven by COVID-19 disruption and a likely recessionary environment, in which the company should beneﬁt.",
        relevancy_score: 1,
        scaled_score: 0.613595552498591,
        semantic_score: 0,
        table: null,
        table_all: null,
        uniq_id: 'c817fc4b',
      },
    ],
    page_idx: 16,
    phrase:
      'Our $105 price target is based on ~19x our 2021e EPS of ~$5.55 (or ~10.5x 2021e EBITDA).',
    relevancy_score: 1,
    scaled_score: 0.999917135005772,
    semantic_score: 0,
    table: null,
    table_all: null,
    uniq_id: 'f4d10248',
  },
];

export default function SearchResultTest() {
  const searchResults = mockSearchData;

  return (
    <div style={{ width: '500px', height: '100vh', overflowY: 'auto' }}>
      <SearchResult
        searchResults={searchResults}
        resultHandler={() => {}}
        showCriteria={false}
        // selectedSearchCriteria={fieldData}
        showCreateFieldButton={false}
      ></SearchResult>
    </div>
  );
}
